server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms_generalsetup
    username: root
    password: Vishal#184200
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
debug: true
#feign:client:config:default:connect-timeout:5000read-timeout: 5000
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

authservice:
  url: http://localhost:8080  # Replace with the actual URL of authservice
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true


#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#  hystrix:
#    enabled: true